spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ce    # ?? ??? ?? DB??? ??
    username: postgres                          # ?? DB ??
    password: '#vmfhwprxm12'                    # ?? ????
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none          # ??? ?? DDL ?????? none/validate ??
    show-sql: true            # ??? SQL ???
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect